version: "3.4"
services:
  covid19graphql:
    container_name: projectapp
    build: .
    environment:
      - FLASK_RUN_HOST=projectapp
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=True
      - DB_HOST=project_db
      - DB_Name="covid19"
      - DB_Port=27017
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    links:
      - mongo
  mongo:
    container_name: project_db
    restart: always
    image: mongo:latest
    ports: 
      - "27016:27017"
